version: '3'

services:
  murmur:
    image: goofball222/murmur
    container_name: murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - ./murmur.ini:/etc/murmur.ini
    environment:
      - TZ=UTC

  mumo:
    image: goofball/mumo
    container_name: mumo
    network_mode: service:murmur
    depends_on:
      - murmur
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/opt/mumo/config
      - ./log:/opt/mumo/log
    environment:
      - TZ=UTC
